version: '3'

services:
  centos7:
    image: indexyz/ansible:centos-7
    build:
      context: ./dockerfiles/centos
      dockerfile: 7.Dockerfile

  centos8:
    image: indexyz/ansible:centos-8
    build:
      context: ./dockerfiles/centos
      dockerfile: 8.Dockerfile

  debian9:
    image: indexyz/ansible:debian-9
    build:
      context: ./dockerfiles/debian
      dockerfile: 9.Dockerfile

  archlinux:
    image: indexyz/ansible:archlinux
    build:
      context: ./dockerfiles/archlinux
      dockerfile: Dockerfile
